language: objective-c
os: osx
osx_image: xcode9.3
node_js: 10

cache:
- bundler
- pip
- yarn

before_install:
- brew update
- brew install yarn
- cd angelfish-pos

before_script:
- nvm install 10
- sudo easy_install virtualenv
- virtualenv ~/virtualenv
- source ~/virtualenv/bin/activate

script:
- npm test
