language: objective-c
os: osx
osx_image: xcode9.3
node_js: node

cache:
- bundler
- pip
- yarn

before_install:
- brew update
- brew install yarn
- cd angelfish-pos

install:
- npm ci

before_script:
- nvm install node
- sudo easy_install virtualenv
- virtualenv ~/virtualenv
- source ~/virtualenv/bin/activate

script:
- npm test
